<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: NewArchive

//* Remove standard post content output
//remove_action( 'genesis_post_content', 'genesis_do_post_content' );
//remove_action( 'genesis_entry_content', 'genesis_do_post_content' );
//remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
//remove_action( 'genesis_entry_header', 'genesis_post_info');
//remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_open', 5 );
//remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_close', 15 );

//add_action('genesis_entry_header','taiphuong_do_post');

function taiphuong_do_post(){
  $title = apply_filters( 'genesis_post_title_text', get_the_title() );

  	if ( 0 === mb_strlen( $title ) )
  		return;

  	//* Link it, if necessary
  	if ( ! is_singular() && apply_filters( 'genesis_link_post_title', true ) ){
  		$title = sprintf( '<a href="%s" rel="bookmark">%s</a>', get_permalink(), $title );
  	}

  	//* Wrap in H1 on singular pages
  	$wrap = is_singular() ? 'h1' : 'h3';

  	//* Also, if HTML5 with semantic headings, wrap in H1
  	$wrap = genesis_html5() && genesis_get_seo_option( 'semantic_headings' ) ? 'h4' : $wrap;

  	/**
  	 * Entry title wrapping element
  	 *
  	 * The wrapping element for the entry title.
  	 *
  	 * @since 2.2.3
  	 *
  	 * @param string $wrap The wrapping element (h1, h2, p, etc.).
  	 */
  	$wrap = apply_filters( 'genesis_entry_title_wrap', $wrap );

  	//* Build the output
  	$output = genesis_markup( array(
  		'html5'   => "<{$wrap} %s>",
  		'xhtml'   => sprintf( '<%s class="entry-title">%s</%s>', $wrap, $title, $wrap ),
  		'context' => 'section-heading',
  		'echo'    => false,
  	) );

  	$output .= genesis_html5() ? "{$title}</{$wrap}>" : '';

  	echo apply_filters( 'genesis_post_title_output', "$output \n" );
  
}



//add_action( 'genesis_entry_content', 'genesis_page_archive_content' );
//add_action( 'genesis_post_content', 'genesis_page_archive_content' );
/**
 * This function outputs sitemap-esque columns displaying all pages,
 * categories, authors, monthly archives, and recent posts.
 *
 * @since 1.6
 */
function genesis_page_archive_content() {
echo "Phương tài";
}



genesis();